### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by zRiaz** [drtshock/HomeLimit#1]
Bugs:
Player swofteh; Had essentials.sethome.multiple.VIP (4homes)
Did the command /homelimit swofteh 1
Gets this message: Your new homelimit is now 2?

Tries to set more homes = Gets essentials error message of max homes reached (4)? Am I doing something wrong or wut?

**Comment by drtshock** [comment]
Do you have those permissions defined in the essentials config? You need to do that.

**Comment by zRiaz** [comment]
I have 1:1 2:2 etc defined yes.

**Comment by drtshock** [comment]
Paste your essentials config in a gist please.

**Comment by zRiaz** [comment]
Will do when I get home.
But I listed it like this:
Donator: 2
VIP: 4 and so on, then I added;
1: 1
2: 2
3: 3
4: 4
(When I think about it, I might have forgotten the space between 1: 1 and so on. Ill look when I get home.

**Comment by zRiaz** [comment]
# Allow players to have multiple homes.
# Players need essentials.sethome.multiple before they can have more than 1 home.
# You can set the default number of multiple homes using the 'default' rank below.
# To remove the home limit entirely, give people 'essentials.sethome.multiple.unlimited'.
# To grant different home amounts to different people, you need to define a 'home-rank' below.
# Create the 'home-rank' below, and give the matching permission: essentials.sethome.multiple.<home-rank>
# For more information, visit http://wiki.ess3.net/wiki/Multihome
sethome-multiple:
  Owner: 25
  Admin: 25
  YouTube: 10
  Donator: 2
  VIP: 4
  Elite: 6
  Lord: 9
  Champion: 13
  Immortal: 15
  Zeus: 18
  Brawler: 21
  1: 1
  2: 2
  3: 3
  4: 4
  5: 5

**Comment by zRiaz** [comment]
# For more information, visit http://wiki.ess3.net/wiki/Multihome

sethome-multiple:
  Owner: 25
  Admin: 25
  YouTube: 10
  Donator: 2
  VIP: 4
  Elite: 6
  Lord: 9
  Champion: 13
  Immortal: 15
  Zeus: 18
  Brawler: 21
  1: 1
  2: 2
  3: 3
  4: 4
  5: 5

**Comment by drtshock** [comment]
Paste your ENTIRE essentials config in a pastebin or gist.

**Comment by zRiaz** [comment]
http://pastebin.com/P4kAF2HN

**Comment by zRiaz** [comment]
So?

**Comment by drtshock** [comment]
You can only use numbers with this. It doesn't work with named permissions.

**Comment by zRiaz** [comment]
Do you mean already named permissions?
